name: Build Library
run-name: "${{ github.action }}: ${{ github.ref_name }}"
on:
  push:
    # paths-ignore:
    #   - '**/*.md'
    # branches:
    #   - main
  pull_request:
    # branches:
    #   - main
    # paths-ignore:
    #   - '**/*.md'
  workflow_dispatch:

env:
  # Configuration type to build.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    # 2019 has our .NET needs, and is the fastest.
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        project: [Elements.Quantity, Testing]

    # Cancels previous runs if they're still in progress.
    # It's unlikely with how short this workflow is, but it's good to have.
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.project }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        dotnet restore ${{ matrix.project }} --no-dependencies

    - name: Build
      run: |
        dotnet build ${{ matrix.project }} --no-restore

  testing:
    # Why test if we don't build?
    needs: build
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        project: [Elements.Quantity, Testing]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        dotnet restore ${{ matrix.project }} --no-dependencies

    - name: Test
      run: |
        dotnet test ${{ matrix.project }} --verbosity normal --no-restore
