name: Build Library

on:
  push:
    # paths-ignore:
    #   - '**/*.md'
    # branches:
    #   - main
  pull_request:
    # branches:
    #   - main
    # paths-ignore:
    #   - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    # Cancels previous runs if they're still in progress.
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    # 2019, has our .NET needs, latest does not
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        dotnet restore Elements.Quantity
        dotnet restore Testing
    # It is faster to call dotnet build on the projects than to call dotnet build on the solution.
    - name: Build
      run: |
        dotnet build Elements.Quantity --configuration Release
        dotnet build Testing --configuration Release
    - name: Test
      run: dotnet test Testing -c Release --verbosity normal
