name: Build Library
run-name: "[${{ github.workflow }}${{ (github.run_attempt == 1) && (']') || (format(' | Attempt #{0}]', github.run_attempt)) }} ${{ github.event.head_commit.message }}"
on:
  push:
    # paths-ignore:
    #   - '**/*.md'
    # branches:
    #   - main
  pull_request:
    # branches:
    #   - main
    # paths-ignore:
    #   - '**/*.md'
  workflow_dispatch:

env:
  # Configuration type to build.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    # 2019 has our .NET needs, and is the fastest.
    runs-on: windows-2019

    # Cancels previous runs if they're still in progress.
    # It's unlikely with how short this workflow is, but it's good to have.
    concurrency:
      group: build-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        dotnet restore Elements.Quantity --no-dependencies

    - name: Build
      run: |
        dotnet build Elements.Quantity --no-restore

  testing:
    runs-on: windows-2019

    # Cancels previous runs if they're still in progress.
    # It's unlikely with how short this workflow is, but it's good to have.
    concurrency:
      group: testing-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        dotnet restore Testing --no-dependencies

    - name: Test
      run: |
        dotnet test Testing --verbosity normal --no-restore
