name: Build Library

on:
  push:
    # paths-ignore:
    #   - '**/*.md'
    # branches:
    #   - main
  pull_request:
    # branches:
    #   - main
    # paths-ignore:
    #   - '**/*.md'
  workflow_dispatch:


jobs:
  build:
    # Cancels previous runs if they're still in progress.
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    # 2019, has our .NET needs, latest does not
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    # While this package targets .Net Framework 4.6.2, the dotnet 7 stuff will work.
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    # No deps are needed for this atm.
    # - name: Install dependencies
    #   run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
